### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by Yky** [arkon/CDFLabs#36]
I get the following error when selecting the computers or printers tab: 

"Whoops! We ran into an issue fetching data."

```
08-09 00:28:58.596 W/System.err(21246): org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://cssu.ca/data/cdflabs.json
08-09 00:28:58.597 W/System.err(21246): 	at org.jsoup.helper.HttpConnection$Response.execute(Unknown Source:352)
08-09 00:28:58.597 W/System.err(21246): 	at org.jsoup.helper.HttpConnection$Response.execute(Unknown Source:1)
08-09 00:28:58.597 W/System.err(21246): 	at org.jsoup.helper.HttpConnection.execute(Unknown Source:2)
08-09 00:28:58.597 W/System.err(21246): 	at me.echeung.cdflabs.utils.data.LabDataFetcher.doInBackground(LabDataFetcher.java:23)
08-09 00:28:58.597 W/System.err(21246): 	at me.echeung.cdflabs.utils.data.LabDataFetcher.doInBackground(LabDataFetcher.java:20)
08-09 00:28:58.597 W/System.err(21246): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-09 00:28:58.597 W/System.err(21246): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-09 00:28:58.597 W/System.err(21246): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-09 00:28:58.597 W/System.err(21246): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 00:28:58.597 W/System.err(21246): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 00:28:58.597 W/System.err(21246): 	at java.lang.Thread.run(Thread.java:764)
08-09 00:28:58.693 W/System.err(21246): org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://cssu.ca/data/cdfprinters.json
08-09 00:28:58.693 W/System.err(21246): 	at org.jsoup.helper.HttpConnection$Response.execute(Unknown Source:352)
08-09 00:28:58.693 W/System.err(21246): 	at org.jsoup.helper.HttpConnection$Response.execute(Unknown Source:1)
08-09 00:28:58.693 W/System.err(21246): 	at org.jsoup.helper.HttpConnection.execute(Unknown Source:2)
08-09 00:28:58.693 W/System.err(21246): 	at me.echeung.cdflabs.utils.data.PrinterDataFetcher.doInBackground(PrinterDataFetcher.java:26)
08-09 00:28:58.693 W/System.err(21246): 	at me.echeung.cdflabs.utils.data.PrinterDataFetcher.doInBackground(PrinterDataFetcher.java:23)
08-09 00:28:58.693 W/System.err(21246): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-09 00:28:58.693 W/System.err(21246): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-09 00:28:58.693 W/System.err(21246): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-09 00:28:58.693 W/System.err(21246): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 00:28:58.693 W/System.err(21246): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 00:28:58.693 W/System.err(21246): 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by arkon** [comment]
Yeah, the data files are no longer available ever since I left the university and nobody else maintained the scripts. I've since unpublished this app from the Play Store.
